use_frameworks!

target 'ProtobufSampleApp' do
  pod 'Alamofire', '~> 4.4'
  pod 'SwiftProtobuf', :git => 'https://github.com/apple/swift-protobuf.git', :commit => '74061f9cf1b78e8ebf3d515cb0857b0a7446ea11'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
